[package]
name = "gjallarbot"
description = "My personal 'stuff' Discord bot"
keywords = ["discord", "bot"]
repository = "https://github.com/Angelin01/gjallarbot"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[profile.release]
strip = "debuginfo"
lto = "fat"

[dev-dependencies]
tempfile = "3.13.0"
