[package]
name = "gjallarbot"
description = "My personal 'stuff' Discord bot"
keywords = ["discord", "bot"]
repository = "https://github.com/Angelin01/gjallarbot"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]



[profile.release]
strip = "debuginfo"
lto = "fat"
